# Generated by Django 5.1 on 2024-08-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='documents/%Y/%m/%d/originals/')),
                ('translated_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/translations/')),
                ('translation_language', models.CharField(choices=[('EN', 'Английский'), ('ES', 'Испанский'), ('KZ', 'Казахский'), ('DE', 'Немецкий'), ('FR', 'Французский')], max_length=2)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
