# Generated by Django 5.1 on 2024-08-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='translation_language',
            field=models.CharField(blank=True, choices=[('EN', 'Английский'), ('ES', 'Испанский'), ('KZ', 'Казахский'), ('DE', 'Немецкий'), ('FR', 'Французский')], max_length=2),
        ),
    ]
